"""Initial migration

Revision ID: 357741aa306f
Revises: 7c32b8fecc50
Create Date: 2023-07-19 11:18:34.102397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357741aa306f'
down_revision = '7c32b8fecc50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.alter_column('date_subscribed',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership', schema=None) as batch_op:
        batch_op.alter_column('date_subscribed',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.drop_table('user')
    # ### end Alembic commands ###
